import time
from pynput.mouse import Button, Controller
mouse = Controller()
time.sleep(1)
mouse.position = (428, 542)
time.sleep(0.5)
mouse.press(Button.left)
time.sleep(0.05)
mouse.release(Button.left)
# Click on Pawn Instruction
time.sleep(1)
mouse.position = (312, 314)
time.sleep(0.5)
mouse.press(Button.left)
time.sleep(0.05)
mouse.release(Button.left)
# Back to Instruction Menu
time.sleep(1)
mouse.position = (323, 750)
time.sleep(0.5)
mouse.press(Button.left)
time.sleep(0.05)
mouse.release(Button.left)
# Click on Rook Instruction
time.sleep(1)
mouse.position = (580, 314)
time.sleep(0.5)
mouse.press(Button.left)
time.sleep(0.05)
mouse.release(Button.left)
# Back to Instruction Menu
time.sleep(1)
mouse.position = (323, 750)
time.sleep(0.5)
mouse.press(Button.left)
time.sleep(0.05)
mouse.release(Button.left)
# Click on Knight Instruction
time.sleep(1)
mouse.position = (842, 314)
time.sleep(0.5)
mouse.press(Button.left)
time.sleep(0.05)
mouse.release(Button.left)
# Back to Instruction Menu
time.sleep(1)
mouse.position = (323, 750)
time.sleep(0.5)
mouse.press(Button.left)
time.sleep(0.05)
mouse.release(Button.left)
# Click on Bishop Instruction
time.sleep(1)
mouse.position = (312, 580)
time.sleep(0.5)
mouse.press(Button.left)
time.sleep(0.05)
mouse.release(Button.left)
# Back to Instruction Menu
time.sleep(1)
mouse.position = (323, 750)
time.sleep(0.5)
mouse.press(Button.left)
time.sleep(0.05)
mouse.release(Button.left)
# Click on Queen Instruction
time.sleep(1)
mouse.position = (580, 580)
time.sleep(0.5)
mouse.press(Button.left)
time.sleep(0.05)
mouse.release(Button.left)
# Back to Instruction Menu
time.sleep(1)
mouse.position = (323, 750)
time.sleep(0.5)
mouse.press(Button.left)
time.sleep(0.05)
mouse.release(Button.left)
# Click on King Instruction
time.sleep(1)
mouse.position = (842, 580)
time.sleep(0.5)
mouse.press(Button.left)
time.sleep(0.05)
mouse.release(Button.left)
# Back to Instruction Menu
time.sleep(1)
mouse.position = (600, 750)
time.sleep(0.5)
mouse.press(Button.left)
time.sleep(0.05)
mouse.release(Button.left)
# Test next page function
time.sleep(1)
mouse.position = (312, 314)
time.sleep(0.5)
mouse.press(Button.left)
time.sleep(0.05)
mouse.release(Button.left)
time.sleep(1)
mouse.position = (875, 750)
time.sleep(0.5)
mouse.press(Button.left)
time.sleep(0.05)
mouse.release(Button.left)
time.sleep(1)
mouse.position = (875, 750)
time.sleep(0.5)
mouse.press(Button.left)
time.sleep(0.05)
mouse.release(Button.left)
time.sleep(1)
mouse.position = (875, 750)
time.sleep(0.5)
mouse.press(Button.left)
time.sleep(0.05)
mouse.release(Button.left)
time.sleep(1)
mouse.position = (875, 750)
time.sleep(0.5)
mouse.press(Button.left)
time.sleep(0.05)
mouse.release(Button.left)
time.sleep(1)
mouse.position = (875, 750)
time.sleep(0.5)
mouse.press(Button.left)
time.sleep(0.05)
mouse.release(Button.left)
time.sleep(1)
mouse.position = (600, 750)
time.sleep(0.5)
mouse.press(Button.left)
time.sleep(0.05)
mouse.release(Button.left)
time.sleep(0.5)
mouse.press(Button.left)
time.sleep(0.05)
mouse.release(Button.left)

